### ISSUE TITLE
Error response has password in plain text 

### ISSUE THREAD

**Issue by nagashreeb** [apigee/apigee-api-catalog-drupal#51] opened 2019-10-21 16:33 UTC
The API catalog module endpoint in the apigee kickstart drupal 8 portal, to create the API spec - http://{hostname}/jsonapi/apidoc/apidoc
displays the password in plain text in the error response.

1. Make a HTTP POST call to the endpoint http://{hostname}/jsonapi/apidoc/apidoc with an invalid value in the Content-Type header example: application/vnd.api+json1
2. Examine the response: errors array and the trace array element "Php-Auth-Pw:" has the password in plain text
![api-catalog-password-plaintext](https://user-images.githubusercontent.com/8231422/67249452-93f3c980-f41c-11e9-83d1-75db5f60db26.jpg)

**Expected behavior**
Password should not be shown in plain text

**Screenshots**
Screenshot is attached

**Comment by arunz6161** [comment] 2019-10-21 16:39
Hi @nagashreeb - thanks for reporting the issue with the steps to reproduce. We will prioritize this issue and keep the bug updated with progress we make.

**Comment by arunz6161** [comment] 2019-10-22 22:31
@nagashreeb We were able to reproduce the issue. While not desirable, the impact here is limited as the password is exposed to the user supplying it in first place. Given the impact is limited here, we are likely to prioritize this a little later down in future.

**Comment by cnovak** [comment] 2020-12-08 18:59
I am going to close this issue since this module does not handle authentication, the Drupal core JSON API module does this. We are just building on top of it. It looks like your site may have tracing on, so changing the log level to production settings will most likely stop this from happening. If you still see this being an issue, please report on Drupal.org for the JSON API module.

**Closed as completed by cnovak** 2020-12-08 18:59 UTC
Labels: bug
