### ISSUE TITLE
API Catalogue configuration page gives error

### ISSUE THREAD

**Issue by nishasw** [apigee/apigee-api-catalog-drupal#121] opened 2021-02-02 06:34 UTC
I installed Apigee Kickstart module for Drupal 9 and Drupal 8 using following command as documented on Apigee Kickstart module screen (https://www.drupal.org/node/3058326#s-installation-instructions) :  

composer create-project apigee/devportal-kickstart-project:9.x-dev MY_PROJECT 

Just after the installation of this module, when clicked on configure API Catalogue module (/admin/structure/apidoc) we get following error:  

InvalidArgumentException: Class "Drupal\apigee_api_catalog\Entity\Form\ApiDocSettingsForm" does not exist. in Drupal\Core\DependencyInjection\ClassResolver->getInstanceFromDefinition() (line 24 of core/lib/Drupal/Core/DependencyInjection/ClassResolver.php).  

**Reproduction Steps :**  

1.      Setup Apigee Kickstart Project using following command :  

composer create-project apigee/devportal-kickstart-project:9.x-dev MY_PROJECT 

2.      Login as an admin 

3.      Go to Extend 

4.      Search for API Catalogue module 

5.      Expand the module description 

6.      Click on configure [/admin/structure/apidoc] 

After taking above steps , you will see the error mentioned. 

**Troubleshoot Steps applied so far :** 

1. After debugging for above error , we found that the Product catalogue settings file is missing from the code base.  
2. Also tried to manually install API catalogue module 

API Catalogue module version used in our product setup is 8.x-2.5.

Any help would greatly be appreciated. Thanks in advance.

**Comment by shishir-intelli** [comment] 2021-02-02 09:52
Thanks @nishasw ,

Duplicate of [Issue 451](https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/451), 
For configuring the module please check the comment here [Issue 451 Apigee kickstart](https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/451).

We have identified the bug and will soon create a PR for same.

**Comment by phdhiren** [comment] 2021-02-23 06:28
Closing this issue as well as the duplicate #122 is also solved

**Closed as completed by phdhiren** 2021-02-23 06:28 UTC
Labels: bug
