### ISSUE TITLE
DOCS:  Add documentation re troubleshooting CORS and OAuth with Try It Now functionality

### ISSUE THREAD

**Issue by jbennett13** [apigee/apigee-api-catalog-drupal#49] opened 2019-10-11 17:36 UTC
Add documentation outlining solutions to CORS errors and OAuth issues encountered when using the Try it Now functionality.

**Comment by jbennett13** [comment] 2020-02-04 17:13
Top priority - drafting updates to various sections of Edge and API Catalog docs.

**Comment by giteshk** [comment] 2020-03-24 21:44
Hi Jenn,

When should we expect this documentation to be published?

**Comment by jbennett13** [comment] 2020-03-25 00:21
Hi Gitesh - here is the draft (merging your doc and Chris' with some additions):  https://docs.google.com/document/d/1e3O3dZsk6DpR5kWHGxydhy69EBtqxSiLrg_bdCnQv8k/edit?usp=sharing Can you let me know what you think?  I tried to walk through it on my own, but had 1-2 questions I wanted to confirm.  I can transfer to Drupal.org and publish ASAP.

**Comment by arunz6161** [comment] 2020-03-31 18:10
Duplicate of #68

**Closed as completed by arunz6161** 2020-03-31 18:10 UTC
Labels: documentation
