### ISSUE TITLE
Smartdoc is not working as expected

### ISSUE THREAD

**Issue by KNSivagami** [apigee/apigee-api-catalog-drupal#76] opened 2020-03-23 05:57 UTC
Hi Team,

I have two swaggers, which I have imported into new Apigee Kickstart portal, where i could see some issues in swagger, The swagger is not read properly

1. in OAuth swagger i could not see the place to enter the form param
2. in maxpro swagger, the add circle is not working to add the body params
3. Mail is sent evn after configuring smtp.

PFA swagger and error screen shots, I have installed kickstart in our on-prem aws system.
<img width="392" alt="2020-03-19 18_59_56-OAuth _ Developer Portal Site" src="https://user-images.githubusercontent.com/62534689/77286234-d20d5600-6cf8-11ea-9080-5b94042ee5c6.png">
<img width="489" alt="2020-03-19 19_00_29-OAuth _ Developer Portal Site" src="https://user-images.githubusercontent.com/62534689/77286239-d3d71980-6cf8-11ea-9880-6c09758abced.png">
<img width="484" alt="2020-03-19 19_03_00-Max-pro _ Developer Portal Site" src="https://user-images.githubusercontent.com/62534689/77286241-d46fb000-6cf8-11ea-9045-cce74a041272.png">
<img width="917" alt="2020-03-19 19_04_43-SMTP Authentication Support _ Developer Portal Site" src="https://user-images.githubusercontent.com/62534689/77286243-d5084680-6cf8-11ea-9725-e8542d2c2929.png">
[maxpro.txt](https://github.com/apigee/apigee-api-catalog-drupal/files/4367446/maxpro.txt)
[Oauth.txt](https://github.com/apigee/apigee-api-catalog-drupal/files/4367447/Oauth.txt)

**Comment by arunz6161** [comment] 2020-03-25 01:26
@KNSivagami for the issue with maxpro swagger, could you please mention the resource that we can use to see the problem ?
I am able to reproduce issue with Oauth and will update you with findings. 

Please log a new issue for SMTP in the Apigee Kickstart queue.  In future, please open separate issues instead of clubbing them in one.

**Comment by arunz6161** [comment] 2020-03-25 16:31
@KNSivagami the issue with being unable to enter form param is a known issue ( bug id: 118358600) and this is currently in our backlog being worked upon. We will keep you posted on ETA of the fix. Please provide information about the resource that we can use to reproduce the issue with maxpro swagger?

**Comment by cnovak** [comment] 2020-03-25 16:54
I think the form param is a duplicate of #67 , is that true @arunz6161 @KNSivagami ? If so we should discuss that issue in that ticket so that we can keep issues separate.

As far as SMTP, try enabling debug mode and sending an email. You can then see exact info on the request/responses of the mail server to find out what is going wrong. You can also check the [issue queue or add a new issue to the SMTP module](https://www.drupal.org/project/issues/search/smtp) if you are still having problems.

**Comment by arunz6161** [comment] 2020-04-28 18:49
@KNSivagami Please reopen this if still an issue.

**Closed as completed by arunz6161** 2020-04-28 18:49 UTC
Labels: bug
