### ISSUE TITLE
API Catalog page render issue

### ISSUE THREAD

**Issue by SajithAthukorala** [apigee/apigee-api-catalog-drupal#88] opened 2020-05-20 07:08 UTC
https://github.com/apigee/apigee-api-catalog-drupal/issues/70
@cnovak , @dknezicd Thanks for the patch however we are still having similar issues when we load a API catalog page for the first time. (on a fresh browser session). That too intermittently and the second refresh always fix it.

**Comment by cnovak** [comment] 2020-05-27 18:24
Hi @SajithAthukorala , we put this change into version 1.2 and 2.0 now, can you update to one of those versions and let us know if you see any issues?  

If that does not work, can you give us info on what you are seeing in the developer tools of the browser? Is there any console errors?

**Comment by ravisilva** [comment] 2020-05-28 16:31
Hi @cnovak , We are already on v1.2 . The trouble we had was when we go in to a specification page on a fresh browser session (after clearing the browser cache), the smartdoc component was not loading properly and have to do another page refresh to make it appear.
We had tried this on a vanilla Apigee kickstart set up as well and we could replicate the issue consistently. 

However the workaround mentioned here https://github.com/apigee/apigee-api-catalog-drupal/issues/70#issuecomment-631986435 worked well for us.

Thanks so much!

![image](https://user-images.githubusercontent.com/1794429/83167296-b033b380-a12d-11ea-972d-9d0a7e79d8c1.png)

**Comment by cnovak** [comment] 2020-05-28 17:22
Thanks for feedback @ravisilva , we will work in fixing this issue in our next release so you can remove your workaround.

**Comment by cnovak** [comment] 2020-12-08 18:39
Closing as a duplicate of #70

**Closed as completed by cnovak** 2020-12-08 18:39 UTC
Labels: bug
